// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin-access" | "/assignments" | "/attendance" | "/customer-email-evidence" | "/customer-timesheet-approval" | "/customer/attendance" | "/customer/dashboard" | "/customer/job-sites" | "/customer/timesheets" | "/customers" | "/dashboard" | "/data-import" | "/data-import/history" | "/data-import/reset" | "/documents" | "/email-reply-sync-v2" | "/employees" | "/job-orders" | "/job-sites" | "/login" | "/notifications" | "/portal-access" | "/reports" | "/safety-bulletins" | "/settings" | "/supervisor/attendance" | "/supervisor/dashboard" | "/supervisor/job-sites" | "/supervisor/reports" | "/supervisor/timesheets" | "/supervisors" | "/timesheets"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin-access": {}
  "/assignments": {}
  "/attendance": {}
  "/customer-email-evidence": {}
  "/customer-timesheet-approval": {}
  "/customer/attendance": {}
  "/customer/dashboard": {}
  "/customer/job-sites": {}
  "/customer/timesheets": {}
  "/customers": {}
  "/dashboard": {}
  "/data-import": {}
  "/data-import/history": {}
  "/data-import/reset": {}
  "/documents": {}
  "/email-reply-sync-v2": {}
  "/employees": {}
  "/job-orders": {}
  "/job-sites": {}
  "/login": {}
  "/notifications": {}
  "/portal-access": {}
  "/reports": {}
  "/safety-bulletins": {}
  "/settings": {}
  "/supervisor/attendance": {}
  "/supervisor/dashboard": {}
  "/supervisor/job-sites": {}
  "/supervisor/reports": {}
  "/supervisor/timesheets": {}
  "/supervisors": {}
  "/timesheets": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
