// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-access">> = Specific
  const handler = {} as typeof import("../../src/app/admin-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assignments">> = Specific
  const handler = {} as typeof import("../../src/app/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer-email-evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-email-evidence">> = Specific
  const handler = {} as typeof import("../../src/app/customer-email-evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer-timesheet-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-timesheet-approval">> = Specific
  const handler = {} as typeof import("../../src/app/customer-timesheet-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/customer/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/customer/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/job-sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/job-sites">> = Specific
  const handler = {} as typeof import("../../src/app/customer/job-sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customer/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/customer/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-import/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/history">> = Specific
  const handler = {} as typeof import("../../src/app/data-import/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import">> = Specific
  const handler = {} as typeof import("../../src/app/data-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-import/reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-import/reset">> = Specific
  const handler = {} as typeof import("../../src/app/data-import/reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../src/app/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/email-reply-sync-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/email-reply-sync-v2">> = Specific
  const handler = {} as typeof import("../../src/app/email-reply-sync-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../src/app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-orders">> = Specific
  const handler = {} as typeof import("../../src/app/job-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/job-sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/job-sites">> = Specific
  const handler = {} as typeof import("../../src/app/job-sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portal-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal-access">> = Specific
  const handler = {} as typeof import("../../src/app/portal-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/safety-bulletins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety-bulletins">> = Specific
  const handler = {} as typeof import("../../src/app/safety-bulletins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisor/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/attendance">> = Specific
  const handler = {} as typeof import("../../src/app/supervisor/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/supervisor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisor/job-sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/job-sites">> = Specific
  const handler = {} as typeof import("../../src/app/supervisor/job-sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisor/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/reports">> = Specific
  const handler = {} as typeof import("../../src/app/supervisor/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisor/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/supervisor/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supervisors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisors">> = Specific
  const handler = {} as typeof import("../../src/app/supervisors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
